version: 0.0
os: linux
files:
  - source:  /
    destination: /var/www/html/swaggerpages/
    except:
    owner: ec2-user
    group: apache
permissions:
  - object: /var/www/html/swaggerpages
    owner: ec2-user
    group: apache
    mode: 755
    type:
      - directory
  - object: /var/www/html/swaggerpages
    owner: ec2-user
    group: apache
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
  ApplicationStop:
